// Generated by `cargo test -p eavery-core` (M3-T02). Do not edit.
//
// These are the payloads of the commands and the event in
// `docs/plan/03-architecture.md` §7, straight from the Rust types that
// serialise them. Editing this file by hand only moves the disagreement.
//
// One type per line, in name order: a diff here is a list of the types that
// changed shape, which is the question anyone reviewing this file has.

/**
 * Whether the permission dialog may offer "always" (the last column of
 * §3.2). Serialised for the UI, which knows the mode.
 */
export type AlwaysOffer = "never" | "yes" | "developer_only";

export type AppError = { code: ErrorCode, message: string, 
/**
 * What the person can do about it, in their own words. `None` when there
 * is genuinely nothing to suggest, which the UI renders as a plain
 * report rather than as an instruction.
 */
next_action: string | null, };

/**
 * One decision, on the record. Written by the policy, the plan gate, or the
 * user; never rewritten by any of them.
 */
export type AuditEntry = { seq: number, at: string, project_id: string | null, turn_id: string | null, actor: DecidedBy, 
/**
 * What was decided, in a stable machine-readable form: "allow_once",
 * "plan_approved", "restore". The UI translates; the log does not.
 */
action: string, risk: RiskClass | null, 
/**
 * Whatever the caller wants kept with the decision: the tool call, the
 * paths, the host that was contacted.
 */
detail: unknown, };

/**
 * What changed between two points.
 */
export type ChangeSet = { added: Array<string>, changed: Array<string>, removed: Array<string>, 
/**
 * Unified diffs, for text files only and only under 256 KB. A binary file
 * appears in the lists above and nowhere else.
 */
text_diffs: Array<[string, string]>, };

/**
 * A commit in the Journal. "Checkpoint" is the everyday word for commit.
 */
export type Checkpoint = { id: string, project_id: string, turn_id: string | null, 
/**
 * "Before: rename FY25 → FY26".
 */
label: string, kind: CheckpointKind, created_at: string, files_changed: number, };

export type CheckpointKind = "pre_turn" | "post_turn" | "manual" | "restore";

export type CoreEvent = { "type": "turn_started", turn_id: string, phase: TurnPhase, } | { "type": "phase_changed", turn_id: string, phase: TurnPhase, } | { "type": "agent_text", turn_id: string, text: string, } | { "type": "agent_thought", turn_id: string, text: string, } | { "type": "tool_call_started", turn_id: string, call: ToolCallView, } | { "type": "tool_call_updated", turn_id: string, call: ToolCallView, } | { "type": "plan_updated", turn_id: string, entries: Array<PlanEntryView>, } | { "type": "permission_requested", turn_id: string, request: PermissionView, } | { "type": "permission_resolved", turn_id: string, request_id: string, decision: Decision, by: DecidedBy, } | { "type": "plan_ready", turn_id: string, plan: Plan, vendor: string, } | { "type": "checkpoint_created", checkpoint: Checkpoint, } | { "type": "restored", to: string, new_checkpoint: string, 
/**
 * Files that could not be written because something else held them
 * open. Reported, never silently skipped.
 */
skipped_locked: Array<string>, } | { "type": "turn_finished", turn_id: string, stop_reason: string, digest: Digest | null, } | { "type": "engine_status", engine_id: string, status: EngineStatus, } | { "type": "engine_crashed", engine_id: string, turn_id: string | null, stderr_tail: Array<string>, } | { "type": "error", turn_id: string | null, code: ErrorCode, message: string, 
/**
 * What the user can do about it, in their own vocabulary. Everyday
 * mode renders errors as next actions, not as failures.
 */
next_action: string | null, };

/**
 * Who made a permission decision. Everything is on the record, including the
 * decisions the user never saw.
 */
export type DecidedBy = "policy" | "user" | "plan_gate";

export type Decision = "allow_once" | "allow_always" | "reject_once" | "reject_always" | "cancelled";

/**
 * What the Diagnostics panel shows (`07-ui-vocabulary.md` §3): where the
 * data lives, where the log is, and the end of it.
 */
export type Diagnostics = { 
/**
 * Eavery's own version, from the crate that built the app.
 */
version: string, data_dir: string, log_path: string, 
/**
 * The last lines of the log, oldest first. Empty when there is no log
 * yet, which is not an error: a first run has nothing to say.
 */
log_tail: Array<string>, };

/**
 * What a turn actually did, in file terms.
 */
export type Digest = { files_added: Array<string>, files_changed: Array<string>, files_removed: Array<string>, 
/**
 * What left the machine, from the outbound calls that were allowed. Always
 * rendered, "Nothing" when empty.
 */
outbound_actions: Array<string>, refused_actions: Array<string>, 
/**
 * The pre-turn checkpoint: the one Undo goes back to.
 */
undo_to: string | null, };

/**
 * What an engine reported about itself at `initialize`
 * (`docs/plan/04-acp-engines.md` §1).
 */
export type EngineInfo = { engine_id: string, 
/**
 * `agentInfo.name` from the initialize response, when the engine sends one.
 */
name: string | null, version: string | null, protocol_version: number, 
/**
 * `agentCapabilities.loadSession`: whether `session/load` may be used.
 */
load_session: boolean, 
/**
 * Auth methods the engine advertises. Empty means no auth step is needed.
 */
auth_methods: Array<string>, };

/**
 * One row of the Assistants screen: an engine from the table, and what a
 * health check just said about it (`docs/plan/07-ui-vocabulary.md` §5).
 */
export type EngineListing = { id: string, 
/**
 * The engine's everyday name: "Claude Code", "On this computer".
 */
display_name: string, vendor: string, 
/**
 * Hidden unless Developer mode is on.
 */
experimental: boolean, status: EngineStatus, 
/**
 * Where the executable was found. Developer mode shows it; Everyday mode
 * never does.
 */
program: string | null, };

/**
 * The result of a health check, rendered by
 * `docs/plan/07-ui-vocabulary.md` §5.
 */
export type EngineStatus = { "state": "not_installed", instructions: string, searched: Array<string>, } | { "state": "needs_node" } | { "state": "needs_sign_in", command: string, } | { "state": "installing", percent: number, } | { "state": "signing_in" } | { "state": "ready", info: EngineInfo, modes: Array<SessionMode>, 
/**
 * The mode the engine started in, when it reports modes at all.
 */
current_mode: string | null, } | { "state": "unavailable", reason: string, };

export type ErrorCode = "engine_unavailable" | "engine_timeout" | "engine_crashed" | "checkpoint_failed" | "restore_failed" | "file_locked" | "plan_gate_bypassed" | "turn_already_running" | "project_too_large" | "permission_timeout" | "internal";

/**
 * A Journal as Developer mode describes it: where it is, how much room it
 * takes, and how many loose objects it has collected (C12).
 */
export type JournalInfo = { 
/**
 * The git directory, under Eavery's data folder — never inside the
 * Project.
 */
path: string, size_bytes: number, loose_objects: number, };

/**
 * An MCP server to hand the engine in `session/new`. "Connector" is the
 * everyday word.
 */
export type McpServerSpec = { "transport": "stdio", name: string, command: string, args: Array<string>, 
/**
 * Passed to the server process only. Eavery never writes these to the
 * engine's own config.
 */
env: Array<[string, string]>, } | { "transport": "http", name: string, url: string, headers: Array<[string, string]>, };

export type PermissionOption = { option_id: string, name: string, 
/**
 * `allow_once` | `allow_always` | `reject_once` | `reject_always`.
 */
kind: string, };

export type PermissionView = { 
/**
 * The JSON-RPC id of the `session/request_permission` request, as a string.
 */
request_id: string, tool_call_id: string, title: string, 
/**
 * The ACP tool call `kind`, `other` when the engine omits it. The policy
 * classifies on this and [`Self::locations`]; the provisional [`Self::risk`]
 * below is what the layer that has neither the Project root nor the
 * Connector registry could work out on its own.
 */
kind: string, 
/**
 * The files the call names, absolute as the engine gave them. Empty means
 * the engine did not say what it is about to touch, which is a reason to
 * ask rather than a reason to relax.
 */
locations: Array<string>, risk: RiskClass, 
/**
 * Passed through from ACP so the answer can name an option the engine
 * actually offered.
 */
options: Array<PermissionOption>, 
/**
 * Vocabulary-neutral facts — paths, hosts — for the UI to phrase.
 */
explanation: string, 
/**
 * The engine's `rawInput` for the call, when it sent one. The policy
 * matches Connector names and plan-exit signatures against it.
 */
raw_input: unknown, 
/**
 * Whether the dialog may offer "always", per the decision table
 * (`docs/plan/06-plan-gate-permissions.md` §3.2). The UI applies the
 * mode; the core narrows an answer the table forbids regardless.
 */
always: AlwaysOffer, 
/**
 * For something that would leave the machine: whether the plan listed
 * it. `None` otherwise.
 */
in_plan: boolean | null, 
/**
 * The Connector the call belongs to, when the policy could tell.
 */
connector: string | null, };

/**
 * What the engine says it will do, shown to the user before anything runs.
 */
export type Plan = { summary: string, steps: Array<PlanStep>, files_touched: Array<string>, 
/**
 * Actions that leave the machine: "send email to x", "post to Slack #y".
 */
outbound: Array<string>, irreversible: Array<string>, will_not_do: Array<string>, 
/**
 * The engine's full reply, used when the structured block is missing.
 */
raw_markdown: string, 
/**
 * Free text the user added before approving.
 */
user_edits: string | null, };

/**
 * One entry of the engine's own plan checklist (ACP `plan` update).
 */
export type PlanEntryView = { content: string, priority: string | null, status: string | null, };

export type PlanStep = { text: string, done: boolean, };

/**
 * A folder on disk the user has opened. "Project" is the everyday word for a
 * workspace.
 */
export type Project = { id: string, name: string, 
/**
 * Absolute.
 */
root: string, created_at: string, 
/**
 * The engine last used for this Project, if any.
 */
engine_id: string | null, };

/**
 * What a folder holds, before Eavery commits to protecting it.
 */
export type ProjectScan = { files: number, bytes: bigint, };

/**
 * What going back did: the checkpoint it landed on, and every file something
 * else held open and so was left alone. The second list is never dropped — a
 * partial restore the user does not know about is worse than one that failed.
 */
export type RestoreOutcome = { checkpoint: Checkpoint, skipped_locked: Array<string>, };

/**
 * How hard an action is to take back. Permission prompts are decided on this
 * axis, not on tool type (decision D7).
 */
export type RiskClass = "read" | "reversible" | "execute" | "outbound" | "destructive";

/**
 * One conversation with one engine about one Project.
 */
export type Session = { id: string, project_id: string, engine_id: string, 
/**
 * The ACP `sessionId`, kept for `session/load`.
 */
engine_session_id: string | null, created_at: string, };

/**
 * A mode the engine offers, from `session/new`'s optional `modes`.
 */
export type SessionMode = { id: string, name: string, description: string | null, };

/**
 * What the user has chosen. Small on purpose: anything that belongs to a
 * Project lives on the Project, and secrets never live here at all — they go
 * to the OS keychain (M7-T03).
 */
export type Settings = { mode: UiMode, 
/**
 * The engine a new Project starts with.
 */
default_engine: string | null, };

/**
 * An event as it was stored: the event itself, plus where it sits in the one
 * global sequence the UI counts on.
 */
export type StoredEvent = { 
/**
 * Global across every Session, so a gap is visible to a UI watching one
 * Project (`docs/plan/03-architecture.md` §7).
 */
seq: number, session_id: string, turn_id: string | null, at: string, event: CoreEvent, };

/**
 * A tool call as the UI sees it: already classified, already summarised.
 */
export type ToolCallView = { id: string, title: string, 
/**
 * The ACP kind string, `"other"` when the engine omits it.
 */
kind: string, 
/**
 * `pending` | `in_progress` | `completed` | `failed`.
 */
status: string, locations: Array<string>, risk: RiskClass, 
/**
 * "3 lines changed in report.md".
 */
diff_summary: string | null, };

/**
 * One user request and everything the engine does about it.
 */
export type Turn = { id: string, session_id: string, 
/**
 * What the user typed.
 */
request: string, phase: TurnPhase, plan: Plan | null, pre_checkpoint: string | null, post_checkpoint: string | null, started_at: string, };

/**
 * Where a [`Turn`] is in the plan → approve → execute loop
 * (`docs/plan/06-plan-gate-permissions.md` §1).
 */
export type TurnPhase = "planning" | "awaiting_approval" | "executing" | "done" | "failed" | "cancelled";

/**
 * Which vocabulary the app speaks, and what it does by default
 * (`docs/plan/07-ui-vocabulary.md` §1).
 */
export type UiMode = "everyday" | "developer";

export type Unprotected = { 
/**
 * Relative to the Project root.
 */
path: string, } & ({ "reason": "too_large", bytes: bigint, } | { "reason": "not_downloaded" });

