//! The frontend's types, generated from the Rust ones (M3-T02).
//!
//! The frontend is a renderer: everything it draws comes from `eavery-core`
//! over the IPC contract in `docs/plan/03-architecture.md` §7. Hand-written
//! TypeScript for those payloads would drift the first time a field was
//! renamed, and the drift would show up as a blank pane rather than as an
//! error. So it is generated here, from the same types `serde` writes, and
//! this test fails when what is committed is not what those types produce.
//!
//! Run `cargo test -p eavery-core` to regenerate, then commit the result.

use std::any::TypeId;
use std::collections::BTreeSet;
use std::path::PathBuf;

use eavery_core::engine::McpServerSpec;
use eavery_core::event::CoreEvent;
use eavery_core::journal::{ChangeSet, ProjectScan, Unprotected};
use eavery_core::model::{Checkpoint, EngineStatus, Project, Session, Turn};
use eavery_core::store::{AuditEntry, StoredEvent};
use ts_rs::{Config, TS, TypeVisitor};

/// Everything the frontend is handed. Their dependencies come along on their
/// own, so this list is the IPC surface rather than a list of every type.
fn roots(collect: &mut Collect) {
    collect.visit::<Project>();
    collect.visit::<Session>();
    collect.visit::<Turn>();
    collect.visit::<Checkpoint>();
    collect.visit::<EngineStatus>();
    collect.visit::<CoreEvent>();
    collect.visit::<StoredEvent>();
    collect.visit::<AuditEntry>();
    collect.visit::<ChangeSet>();
    collect.visit::<Unprotected>();
    collect.visit::<ProjectScan>();
    collect.visit::<McpServerSpec>();
}

const HEADER: &str = "\
// Generated by `cargo test -p eavery-core` (M3-T02). Do not edit.
//
// These are the payloads of the commands and the event in
// `docs/plan/03-architecture.md` §7, straight from the Rust types that
// serialise them. Editing this file by hand only moves the disagreement.
//
// One type per line, in name order: a diff here is a list of the types that
// changed shape, which is the question anyone reviewing this file has.

";

fn types_ts() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../apps/desktop/src/types.ts")
}

/// Walks a type and everything it is made of, keeping each declaration once.
struct Collect<'a> {
    cfg: &'a Config,
    seen: BTreeSet<TypeId>,
    /// Keyed by name so the file is in a stable order whatever order the
    /// visitor happens to reach things in.
    declarations: BTreeSet<(String, String)>,
}

impl TypeVisitor for Collect<'_> {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        // A type with nowhere to be exported to is a primitive, a `Vec`, or
        // something else that is written inline where it is used.
        if T::output_path().is_none() {
            return;
        }
        if !self.seen.insert(TypeId::of::<T>()) {
            return;
        }

        let mut declaration = String::new();
        if let Some(docs) = T::docs() {
            declaration.push_str(docs.trim_end());
            declaration.push('\n');
        }
        // `decl` already ends in a semicolon; all this adds is the `export`.
        declaration.push_str("export ");
        declaration.push_str(T::decl(self.cfg).trim_end());
        declaration.push('\n');
        self.declarations.insert((T::ident(self.cfg), declaration));

        T::visit_dependencies(self);
    }
}

fn generate() -> String {
    let cfg = Config::default();
    let mut collect = Collect {
        cfg: &cfg,
        seen: BTreeSet::new(),
        declarations: BTreeSet::new(),
    };
    roots(&mut collect);

    let mut out = String::from(HEADER);
    for (_, declaration) in &collect.declarations {
        out.push_str(declaration);
        out.push('\n');
    }
    out
}

/// Regenerates `apps/desktop/src/types.ts`, and fails if that changed
/// anything. Locally the fix is to commit what this just wrote; in CI it means
/// someone changed a type and did not.
#[test]
fn the_frontends_types_are_the_rust_ones() {
    let path = types_ts();
    let generated = generate();
    let committed = std::fs::read_to_string(&path).unwrap_or_default();

    if committed == generated {
        return;
    }

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("make the folder");
    }
    std::fs::write(&path, &generated).expect("write the bindings");
    panic!(
        "{} was out of date and has been regenerated. Commit it.",
        path.display()
    );
}

/// The two that would be silently wrong rather than loudly missing: a `seq`
/// that arrives as a `bigint` cannot be compared with a number, and a tagged
/// union the frontend switches on has to keep its tag.
#[test]
fn the_shapes_the_frontend_switches_on_are_what_it_expects() {
    let generated = generate();

    assert!(
        generated.contains("seq: number"),
        "seq must be a number, not a bigint:\n{generated}"
    );
    assert!(
        generated.contains(r#"{ "type": "turn_started""#),
        "CoreEvent must stay a tagged union:\n{generated}"
    );
    assert!(
        generated.contains(r#"{ "state": "ready""#),
        "EngineStatus must stay a tagged union:\n{generated}"
    );
}
